### ISSUE TITLE
Not working in `async` context

### ISSUE THREAD

**Issue by geakstr** [lxsmnsyc/solid-labels#13]
In case if you try assign value received from awaited promise to solid-label macro variable, it won't set `async` for wrapper function:

```
let current = $signal(null);

async setter() {
  current = async load();
}
```

This will be transformed to:

```
_setcurrent(() => await note.load());
```

Though it should be something like this I guess?

```
await note.load().then(val => _setcurrent(() => val);
```

**Comment by lxsmnsyc** [comment]
Should be fixed in 0.14.3
