### ISSUE TITLE
nested $component ctf support?

### ISSUE THREAD

**Issue by russelgal** [lxsmnsyc/solid-labels#15]
it looks like the nested component call is not supported
```jsx
const Parent = $component(({ ...rest }): JSX.Element => {
  const Child = $component(({ ...rest }): JSX.Element => {
    return <>Child</>;
  });

  return (
    <>
      <Child />
    </>
  );
});
```

[plugin:solid-labels] Unexpected 'CallExpression' (Expected: Identifier | ObjectPattern | ArrayPattern) (This is an error on an internal node. Probably an internal error. Location has been estimated.)

**Comment by lxsmnsyc** [comment]
I've tested this myself and it seems to be working so I'm closing this.
