### ISSUE TITLE
Support server$ functions

### ISSUE THREAD

**Issue by antmoux** [lxsmnsyc/solid-labels#16]
@lxsmnsyc what do you think?

**Comment by lxsmnsyc** [comment]
It's out-of-scope, my other project might be of interest: https://github.com/lxsmnsyc/thaler

**Comment by lxsmnsyc** [comment]
because this library is only reserved for Solid's APIs, and I have made a library dedicated for server functions anyways.

**Comment by lxsmnsyc** [comment]
Closing because it's irrelevant (out of scope).
