### ISSUE TITLE
Add destructuring defaults to the docs

### ISSUE THREAD

**Issue by DaniGuardiola** [lxsmnsyc/solid-labels#9]
**Edit: the feature is supported, but the docs are outdated**

Solid labels supports destructuring with defaults, but the docs are outdated and, in fact, explicitly state that it's not supported. The docs need to be updated to explain the feature.

**Previous content:**

Taking [this babel plugin](https://github.com/orenelbaum/babel-plugin-solid-undestructure) as an example, it should be doable with `mergeProps`:

```ts
// Default props using `mergeProps`
import { Component } from 'solid-js'
const MyComp: Component<...> = (
  { a = 1, b = 2, c = 3 } = defaultProps
) => {a; b; c;}

//  ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓
import { Component, mergeProps } from 'solid-js'
const MyComp: Component<...> = props => {
  props = mergeProps(defaultProps, { a: 1, b: 2, c: 3 }, props);
  props.a; props.b; props.c;
}
```

Wondering if this is something that could be supported here? Thanks!

**Comment by lxsmnsyc** [comment]
Default props are already supported through `$destructure` and `$component`

Fun fact: the default props feature in that plugin is based on my plugin.

**Comment by DaniGuardiola** [comment]
Oh okay, good to know, seems like the docs are outdated then though:

- https://github.com/lxsmnsyc/solid-labels/blob/main/docs/ctf.md

And follow up question, are they not supported through labels and comments?

- https://github.com/lxsmnsyc/solid-labels/blob/main/docs/labels.md#destructure
- https://github.com/lxsmnsyc/solid-labels/blob/main/docs/comments.md

**Comment by lxsmnsyc** [comment]
they share the same features so yes

**Comment by DaniGuardiola** [comment]
Nice! I'm gonna rename this issue then to focus on the docs.

**Comment by lxsmnsyc** [comment]
Well, that took a while
